### ISSUE TITLE
Allow to pass a header for registering a provider

### ISSUE THREAD

**Issue by victorolinasc** [erlef/oidcc#197]
Keycloak has a nice feature of allowing us to dynamically register an application with an initial token. It is described [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#_initial_access_token). 

Would you accept a PR for making this configurable? I think this is straightforward enough. It can be extracted from the AdditionalConfig map [here](https://github.com/indigo-dc/oidcc/blob/master/src/oidcc.erl#L35) and then used on the async_http_post [here](https://github.com/indigo-dc/oidcc/blob/master/src/oidcc_openid_provider.erl#L185).

I am not 100% familiar with erlang tooling and haven't looked into the tests yet, but if this is OK I can take a stab at it.

Thanks

**Comment by bwegh** [comment]
That sounds like a reasonable PR

**Comment by maennchen** [comment]
Replaced by #239
