### ISSUE TITLE
AllowAlgorithms can be :undefined 

### ISSUE THREAD

**Issue by ns-blee** [erlef/oidcc#287]
### oidcc version

3.0.0 (modified, see summary)

### Erlang version

26

### Elixir version

1.15

### Summary

had to merge in https://github.com/erlef/oidcc/commit/c776fb745a1599903ced790f61d204d0d12446f8
  
### Current behavior

https://github.com/erlef/oidcc/blob/1a45cfe8a4bca8773e5164b970b07926bd325e13/src/oidcc_token.erl#L966-L979

### How to reproduce

`Oidcc.Token.retrieve` || `Oidcc.retrieve_token`

### Expected behavior

Preferably would be populated before use

```erlang
    #oidcc_provider_configuration{
        token_endpoint_auth_signing_alg_values_supported = AllowAlgorithms
    } = ProviderConfiguration,

    % Set AllowAlgorithms to an empty list if undefined
    AdjustedAllowAlgorithms = case AllowAlgorithms of
        undefined -> [<<"HS256">>];
        _ -> [<<"HS256">> | AllowAlgorithms]
    end,
    %AdjustedAllowAlgorithms =
    %    case
    %        lists:member(<<"HS256">>, AllowAlgorithms) or
    %            lists:member(<<"HS384">>, AllowAlgorithms) or
    %            lists:member(<<"HS512">>, AllowAlgorithms)
    %    of
    %        true -> AllowAlgorithms;
    %        false -> [<<"HS256">> | AllowAlgorithms]
    %    end,
```

**Comment by maennchen** [comment]
@ns-blee That doesn't make a lot of sense. The metadata property is optional and does not define a default.
Therefore the method `client_secret_jwt` can't work properly if it is not defined.

I think the standard compliant solution is to just fall back to the next auth mechanism if this field is undefined.

**Comment by ns-blee** [comment]
@maennchen `lists:member(<<"HS256">>, AllowAlgorithms)` <- panics here AllowAlgorithms not a list its :undefined...

from available metadata 
"id_token_signing_alg_values_supported":["RS256"]
"request_object_signing_alg_values_supported":["HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"]
"code_challenge_methods_supported":["S256"]

**Comment by ns-blee** [comment]
@maennchen  just to be clear...

the summary is simply related to the version see 'had to merge in https://github.com/erlef/oidcc/commit/c776fb745a1599903ced790f61d204d0d12446f8'

oidcc version

3.0.0 (modified, see summary)

this is simply for the sake of clarity and is not related 

the code provided is the fix not the merged commit

**Comment by maennchen** [comment]
@ns-blee I understand that, thanks for the detailed report.

I'm however not sure if your fix is standard compliant nor that the existing code is looking at it now.

I believe we should just skip  the authentication method if the property is either not defined or does not contain any supported `HS` algorithms.

**Comment by ns-blee** [comment]
@maennchen given `/.well-known/openid-configuration` why did it fail?

**Comment by maennchen** [comment]
The only hint about this in the standard seems to be this: `Servers SHOULD support RS256`. If this in fact means that we can just assume that the server always supports this, I'm not that sure about.

Another certified implementation seems to even crash on purpose in this case:
https://github.com/panva/node-openid-client/blob/a84d022f195f82ca1c97f8f6b2567ebcef8738c3/lib/helpers/client.js#L30

I'll have a look at the start of next week to see how the conformance suite expects to handle this specific case.

I tend more towards skipping this auth method entirely right now if the config is missing.

**Comment by maennchen** [comment]
> @maennchen given `/.well-known/openid-configuration` why did it fail?

There's for sure a bug. I'm just not sure what the correct solution to the bug is.

**Comment by ns-blee** [comment]
> The only hint about this in the standard seems to be this: `Servers SHOULD support RS256`. If this in fact means that we can just assume that the server always supports this, I'm not that sure about.
> 
> Another certified implementation seems to even crash on purpose in this case: https://github.com/panva/node-openid-client/blob/a84d022f195f82ca1c97f8f6b2567ebcef8738c3/lib/helpers/client.js#L30
> 
> I'll have a look at the start of next week to see how the conformance suite expects to handle this specific case.
> 
> I tend more towards skipping this auth method entirely right now if the config is missing.

If the standard says `Servers SHOULD support RS256`. I think its best to make the assumption its supported and fail to auth if not correct. "Trust, but verify"

**Comment by maennchen** [comment]
@ns-blee The issue with that assumption is that the redirect will fail in a way that is not recoverable to the user if the server does not support it. This is not a MUST…

**Comment by maennchen** [comment]
@ns-blee After some though I think it makes sense to assume `HS256` support if the config option is not present.

If we see in the future, that this causes problems, we can still change to just skip in that instance.

A PR for that would be welcome.

**Comment by maennchen** [comment]
Closed in favor of PR

**Comment by paulswartz** [comment]
@ns-blee was there a particular OP you were using where it supported `HS256` but didn't declare it?
