### ISSUE TITLE
Clearly specify the minimum requirement for OTP26

### ISSUE THREAD

**Issue by jozuas** [erlef/oidcc#296]
### Description

There is no communication in this project on the fact that a minimum Erlang OTP version 26 is required.

```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function :base64.encode/2 is undefined or private
```

[`base64.encode/2`](https://www.erlang.org/doc/man/base64.html#encode-2) was introduced in OTP 26

versions:
- oidc: 3.1.0
- Elixir 1.15.7 with Erlang 25.3.2.7

**Comment by maennchen** [comment]
The version is specified for rebar:

https://github.com/erlef/oidcc/blob/6d28af86770dccde52b53659b16baa6783fefae9/rebar.config#L3

Unfortunately, mix does not have a field to do the same thing.

**Comment by jozuas** [comment]
Thanks a lot for your quick response. I've bumped the discussion on this topic on the elixir forum https://elixirforum.com/t/specifying-minimal-erlang-version-in-mix-exs/39911/13?u=jozuas.

For the time being maybe having a visible section in the `README.md` on how "OTP26 or above is required" would ensure a smoother experience for Elixir users?

**Comment by maennchen** [comment]
@jozuas A PR for the README would be welcome :+1: 

Would you provide one?

If yes: make sure the section looks good both on GitHub and also in the docs since the README is included there as well.

**Comment by jozuas** [comment]
Sure, I will do later today.
